### ISSUE TITLE
No result for infinite time.

### ISSUE THREAD

**Issue by lazovskih** [rickypc/selenium-page-object-generator#18]
No result for infinite time.

Hi guys.

Thanks for the great product! Just came across your plugin today. Was happy to see it and install.
Unfortunately, the plugin did not generate any results for most page. Actually I was not able to get results for some pages. Here is the page I was able to produce results: http://demoqa.com/
This page did not produce any results: https://en.wikipedia.org/wiki/Main_Page

Please make let us know if you have time to check the issue and fix.
By the way there are few 'reviews' stating the same problem.

Thanks!

**Comment by gregma** [comment]
With the chrome plugin, I'm able to grab http://demoqa.com/ but the same issue with the wiki page.  Also www.costo.com sits there indefinitely.

**Comment by vasudarch** [comment]
Any solution for 'No result' for infinite time.

**Comment by rickypc** [comment]
This should be fixed in version 1.3.1. You might need to re-install the extension to allow you to accept the download permission request. Please reopen this issue if you still come across the same issue. Closing...
