### ISSUE TITLE
Ability to exclude some WebElements?

### ISSUE THREAD

**Issue by williamrussellajb** [rickypc/selenium-page-object-generator#2]
Hello, 

This project is awesome, thank you.
One problem I'm having is that my webSite has a scrollable text field for checkbox's, they are all prefixed with cat_someLongId

When I generate this page, it's generating around 7,000 elements that I dont need... and impossible to clean up. 

Is there any way i can exclude based on some text or prefix_string? 

Thanks

**Comment by rickypc** [comment]
Thanks, William.

You can modify the options by going to Options > Nodes > Selector and adjust **input** to **input:not([id^="cat_"])** as screenshot below, that would ignore any input tag that has **cat_** prefix. Please don't forget to save it. You can always reset to original settings later.

![ignore-prefix](https://cloud.githubusercontent.com/assets/1145955/9560589/3ec94ed0-4dd1-11e5-895c-0dfb5f32f504.png)

For more information about attribute selector, it can be find in [this Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
