### ISSUE TITLE
Bad code generated

### ISSUE THREAD

**Issue by adamf663** [rickypc/selenium-page-object-generator#3]
Tried plugin;  it generates some bad code.
1)   clickl method out of nowhere followed by invalid java code.
/**
     * Submit the form to target page.
     *
     * @return the GoogleHomePage class instance.
     */
    public GoogleHomePage submit() {
	        clickI&#x27;mFeelingLuckyButton();
        return this;
    }
2) WebDriverWait, ExpectedCondition

If necessary I can post the code, or you can simply go to google.com and run the plugin to generate a java page object model class.

**Comment by rickypc** [comment]
Good catch, Adam. Should be fixed in version 1.2.5. Please reopen otherwise.

**Comment by adamf663** [comment]
Also:  it doesn't handle tables properly.  It generated a separate element/click/set for every cell.
No biggie;  I'll hand edit to handle such cases.

It's a great tool and I expect it to be a tremendous time saver.

----- Original Message -----
