### ISSUE TITLE
(Feature Request) Would love a way to exclude sections by jquery selector

### ISSUE THREAD

**Issue by emragins** [rickypc/selenium-page-object-generator#4]
In particular, I'm thinking that I'd like to use this feature to exclude common page sections like navigation, footer links, etc.

I'd be willing to help to get this implemented -- I looked briefly at the code but I haven't dove in enough to know the best place to inject this.

**Comment by rickypc** [comment]
@emragins, you can modify the options by going to Options > Nodes > Selector and adjust the selector to your need. You can use css selector :not([id^="navigation"]), that would ignore any HTML tag that has id with navigation prefix. Please don't forget to save it. You can always reset to original settings later.

**Comment by emragins** [comment]
Thanks! For some reason I passed over that since my brain focused in on the 'angular part'... and it didn't occur to me to use a :not selector.  I haven't tried it out yet, but it sounds like it should work just fine. :)
