### ISSUE TITLE
Command line version support (nodejs preferred)

### ISSUE THREAD

**Issue by ultrasonicsoft** [rickypc/selenium-page-object-generator#5]
Hi Richard,

I have installed this extension and loved it.

This works great as an browser extension. However I want to run this from command prompt as a node.js script. The extension uses the page that is already loaded, for the command prompt version, I want to provide a HTML source file instead. I should also have option to provide argument as JAVA/C#/ROBOT. The command line arguments should be something like this:

$node page_test_generator.js input.html JAVA

I am good in Nodejs, so if you please provide me what all files I have to change to achieve my requirement, I will fork your branch and do the changes. If it is easy for you to do above changes that would be great otherwise I will make changes as per your guidance.

Thanks!

Best Regards,
Balram

**Comment by rickypc** [comment]
Hi Balram,

That's a great idea. Unfortunately I need to do some cleanups and refactor the files to support Node.JS . I'll look into it.

**Comment by rickypc** [comment]
Balram,

I created a package in NPM registry: https://www.npmjs.com/package/selenium-page-object-generator
Please give it a try and let me know your feedback. Thanks.

**Comment by ultrasonicsoft** [comment]
Hi Richard,

I did write nodejs version of your tool by utilizing your js files and generated test case files from command line as I wanted it quickly and I assumed you were busy.

Your tool is great with extension as well as nodejs package as well. Great work!

Thank you!
