### ISSUE TITLE
Angular JS uncaught exception handler:8

### ISSUE THREAD

**Issue by xavilage** [rickypc/selenium-page-object-generator#7]
Hi @rickypc ,
Your chrome plugin does an awesome work but unfortunately is not working for our **Angular JS** app  in **Java** or **C#**. (yes it works in Robot Framework).

Here you have a AngularJS sample website presenting the same exception than in ours.  
http://cburgdorf.github.io/angular-todo-app/#/main

Would you have a look?

![2016_02_25_11_43_11_angular_todo_app](https://cloud.githubusercontent.com/assets/12712826/13318868/564f08ac-dbb5-11e5-87ba-811e3b6da33e.png)

Thanks in advance,
Kind regards.
Javier Lage

**Comment by rickypc** [comment]
Thank you, @xavilage for reporting the problem. This should be fixed in version 1.2.9. Please reopen otherwise.

**Comment by xavilage** [comment]
Thank you @rickypc. Good job.
