### ISSUE TITLE
Error in event handler: not a valid selector

### ISSUE THREAD

**Issue by skirge** [rickypc/selenium-page-object-generator#9]
My application has following HTML element:

`<a href="javascript:__doPostBack('ctl00$maincontent$FunctionalityProjektTabContainer$KorespondencjaTabPanel$KorespondencjaTab$KorespondencjaTabContainer$PrzychodzaceTabPanel$PrzychodzaceControlGrid$KorespondencjaGridView','Sort$NumerOdbiorcy')">Numer pisma</a>
`
While trying to save page object nothing is generated and following error is visible on Javascript console:

> extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: SyntaxError: Failed to execute 'querySelectorAll' on 'Document': 'a[href='javascript:__doPostBack('ctl00$maincontent$FunctionalityProjektTabContainer$WnioskiPlatnoscTabPanel$WnioskiPlatnoscTab$UmowyGridView$ctl03$WnioskiOPlatnoscGridView','Sort$NumerWniosku')']' is not a valid selector.

**Comment by BogdanLivadariu** [comment]
@skirge I guess your problem might get fixed by #8

**Comment by VaccinalBowl** [comment]
@skirge [#8](https://github.com/rickypc/selenium-page-object-generator/pull/8) should fix this issue. Or at least suppress it.

**Comment by rickypc** [comment]
This should be fixed in version 1.3.0. Please reopen this issue when that is not the case. Closing...
